import React, { CSSProperties, useState } from 'react';

import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import Logo from '../components/logo';
import Link from 'next/link';

const BASE_TITLE = 'reNFT - Rent & Lend NFTs';

export type LayoutProps = {
    documentTitle?: string;
};

export type Layout = React.FC<React.PropsWithChildren<LayoutProps>>;

export const BaseLayout: Layout = ({
    children,
    documentTitle,
}) => {
    const title = `${documentTitle ? `${documentTitle} - ` : ''}${BASE_TITLE}`;

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta
                    name="description"
                    content="Generated by @rainbow-me/create-rainbowkit"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div
                id="layout"
                data-testid="<BaseLayout />"
                className='p-6 flex flex-col justify-between h-screen items-stretch'
            >
                <nav className="w-full flex flex-row justify-between items-center">
                    <Link shallow legacyBehavior href={'/'}>
                        <a>
                            <Logo />
                        </a>
                    </Link>
                    <ConnectButton />
                </nav>
                <main className='p-4 lg:p-8 flex-1 h-full' role='presentation'>
                    {children}
                </main>
                <footer className={styles.footer}>
                    <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
                        Made with ❤️ by your frens at 🌈
                    </a>
                </footer>
            </div>
        </>
    );
};
